# Generated by Django 5.1.5 on 2025-02-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_question_options_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='forms.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='trigger_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
