# Generated by Django 5.1.5 on 2025-02-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_question_parent_question_question_trigger_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="include_in_calculation",
            field=models.BooleanField(default=True),
        ),
    ]
