# Generated by Django 5.1.5 on 2025-02-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0004_question_include_in_calculation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="include_in_calculation",
        ),
        migrations.AddField(
            model_name="question",
            name="include_in_calculations",
            field=models.BooleanField(
                default=False, verbose_name="Include in totals/averages"
            ),
        ),
    ]
